lista = [
       {'pregunta': '¿Cuál es la moneda de México?', 'a': 'Peso', 'b': 'Dolar', 'c':'Euro' ,'correcta': 'a'}, 
       {'pregunta': '¿De qué colores es la bandera de Japón?', 'a': 'Azul y Amarilla','b': 'Blanca y roja', 'c':'Celeste y Blanca' ,'correcta': 'b'}, 
       {'pregunta': '¿Cuántos elementos forman la Tabla Periódica?', 'a': '118', 'b': '123', 'c':'125' ,'correcta': 'a'},
       {'pregunta': '¿Quién pintó la Mona Lisa?', 'a': 'Dali', 'b': 'Miguel Angel', 'c':'Leonardo da Vinci' ,'correcta': 'c'},
       {'pregunta': '¿Qué elemento de la tabla periódica tiene como símbolo He?', 'a': 'Hielo', 'b': 'Helio', 'c':'Litio' ,'correcta': 'b'},
       {'pregunta': '¿Qué planeta es el que se encuentra más cerca del Sol?', 'a': 'Mercurio', 'b': 'Marte', 'c':'Jupiter' ,'correcta': 'a'},
       {'pregunta': '¿A cuántos kilómetros equivale una milla?', 'a': '3.6 km.', 'b': '2.6 km.', 'c':'1.6 km.' ,'correcta': 'c'},
       {'pregunta': '¿De dónde es originario el mojito?', 'a': 'Cuba', 'b': 'Puerto Rico', 'c':'El Salvador' ,'correcta': 'a'},
       {'pregunta': '¿Cuántos lados tiene un heptadecágono?', 'a': 'Dieciseis', 'b': 'Diecisete', 'c':'Quince' ,'correcta': 'b'},
       {'pregunta': '¿De dónde sale el aceite de oliva?', 'a': 'aceitunas', 'b': 'girasol', 'c':'maiz' ,'correcta': 'a'},
       {'pregunta': '¿Dónde nació la pizza?', 'a': 'Roma', 'b': 'Venecia', 'c':'Napoles' ,'correcta': 'c'},
       {'pregunta': '¿Cuál es la capital de Kenia?', 'a': 'Luanda', 'b': 'Nairobi', 'c':'El Cairo' ,'correcta': 'b'},
       {'pregunta': '¿Cuántos colores tiene el cubo Rubik?', 'a': '6', 'b': '9', 'c':'4' ,'correcta': 'a'},
       {'pregunta': '¿A qué país pertenece la Isla de Pascua?', 'a': 'Argentina', 'b': 'Chile', 'c':'Brasil' ,'correcta': 'b'},
       {'pregunta': '¿Cuál es el país más grande del mundo?', 'a': 'China', 'b': 'Canada', 'c':'Rusia' ,'correcta': 'c'},
       {'pregunta': '¿Cuál es el lugar más frío de la tierra?', 'a': 'Rusia', 'b': 'Antartida', 'c':'Groenlandia' ,'correcta': 'b'},
       {'pregunta': '¿Cuál es el río más largo del planeta?', 'a': 'Amazonas', 'b': 'Nilo', 'c':'Misisipi' ,'correcta': 'a'},

       #NUEVAS PREGUNTAS
       {'pregunta': '¿Que obtienes mezclando verde y rojo?', 'a': 'Azul', 'b': 'Naranja', 'c':'Amarillo' ,'correcta': 'c'},
       {'pregunta': '¿En que año salio la primera PlayStation?', 'a': '1994', 'b': '1995', 'c':'1996' ,'correcta': 'a'},
       {'pregunta': '¿A que equivale X en: 2 + (X / 2) = 10?', 'a': '8', 'b': '12', 'c':'16' ,'correcta': 'c'},
       {'pregunta': '¿Que animal acuatico puede regenerar sus partes?', 'a': 'Pez Globo', 'b': 'Estrella de mar', 'c':'Calamar' ,'correcta': 'b'},
       {'pregunta': '¿Que constelacion es conocida como "El Cazador"?', 'a': 'Orion', 'b': 'Sagitario', 'c':'Andromeda' ,'correcta': 'a'},
       {'pregunta': '¿Que planeta de los nombrados tiene anillos?', 'a': 'Neptuno', 'b': 'Urano', 'c':'Saturno' ,'correcta': 'c'},
       {'pregunta': '¿En que año se invento el Avion?', 'a': '1914', 'b': '1903', 'c':'1932' ,'correcta': 'b'},
       {'pregunta': '¿Donde queda ubicado San Marino?', 'a': 'Oceania', 'b': 'America', 'c':'Europa' ,'correcta': 'c'},
       {'pregunta': '¿Cual de estos materiales es conductor electrico?', 'a': 'Oro', 'b': 'Piedra', 'c':'Hidrocarburo' ,'correcta': 'a'},
       {'pregunta': '¿En que plataforma salio el primer juego de Mario?', 'a': 'Consola', 'b': 'Arcade', 'c':'Computadora' ,'correcta': 'b'}
]
